name: Scala CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 11 ] # , 12, 13 ]
      
    steps:       
      - uses: actions/checkout@v1
        with:
          max-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          fetch-depth: 1

      - name: Run tests
        run: sbt test

  no-container:
    runs-on: [ubuntu-latest]
    services:
      nginx:
        image: nginx
        ports:
          - 80
        env:
          NGINX_PORT: 80         
    steps:
     - run: uname -r
     - run: wget -O- http://nginx:${{ services.nginx.ports['80'] }}
       continue-on-error: true       
     - run: wget -O- http://localhost:${{ services.nginx.ports['80'] }}
       continue-on-error: true

  with-container:
    runs-on: [ubuntu-latest]
    container: busybox
    services:
      nginx:
        image: nginx
        ports:
          - 80
        env:
          NGINX_PORT: 80         
    steps:
     - run: uname -r
     - run: wget -O- http://nginx:${{ services.nginx.ports['80'] }}
       continue-on-error: true       
     - run: wget -O- http://localhost:${{ services.nginx.ports['80'] }}
       continue-on-error: true



