name: Scala CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 12, 13 ]
      
    steps:       
      - uses: actions/checkout@v1
        with:
          max-depth: 1

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.${{ matrix.java }}

      - name: Cache .sbt
        uses: actions/cache@v1
        with:
          path:  ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt

      - name: Cache .ivy2
        uses: actions/cache@v1
        with:
          path:  ~/.ivy2
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-ivy2

      - name: Cache .coursier
        uses: actions/cache@v1
        with:
          path:  ~/.coursier
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier

      - name: "Code style check"
        run: sbt scalafmtCheck || { echo "[error] Unformatted code found. Please run 'Test/compile' and commit the reformatted code."; false; }
        continue-on-error: true

      - name: "Build code style check"
        run: sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
        continue-on-error: true

      - name: "Run all tests"
        run: sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M ++2.13.1 clean test
        
      - name: "Slack me"
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: GitHub CI
          text: You rock!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        
